### ISSUE TITLE
Duplicate log entries

### ISSUE THREAD

**Issue by bob9** [80dB/serilogj#3]
I seem to be getting duplicate log entries in seq. I'm using the exact demo code in the serilogj and running seq 3.4.20.

**Comment by 80dB** [comment]
I just tested this. Compiled and executed JavaConsole in InteliJ. 

Waited a bit, checked my (fresh installed) seq 3.4.20 and there's 2 'test' lines, but the JavaConsole application also log's 'test' twice (but with different values for 'blaat').

The log file also has 'test' twice but again, the JavaConsole logs 'test' twice.

So I can't really reproduce the issue.

I do remember an old bug that caused it to send lines twice sometimes. But that was solved a while ago. We've been using this library in our production environment for a while now and it seems rather stable.

**Comment by bob9** [comment]
I resolved this issue it was related to initializing the logger before springboot initiallized..

**Comment by bob9** [comment]
this for your assistance..
