### ISSUE TITLE
not able to correctly configure seq

### ISSUE THREAD

**Issue by mjnorman** [80dB/serilogj#4]
Attempting to configure via--
```
LoggingLevelSwitch levelswitch;
		
Log.setLogger(new LoggerConfiguration()
	.writeTo(seq("http://XXX"), levelswitch));
```

Presented with this error message:
`The method seq(String) is undefined for the type setupSerilog`

setupSerilog is the name of the servlet within which I am trying to invoke this logger config.  Also this is being used within the context of Avaya's Orchestration Designer which is a module for Eclipse.  Any thoughts?

**Comment by mjnorman** [comment]
Silly me forgot to include the .createLogger().

However I'm missing how to configure the logger to be controlled by the levelswitch?

**Comment by 80dB** [comment]
You can use a level switch (like you did in your code example), you can set a minimum level in it and that specific sink will obey the levelswitch. The idea behind it is that you can change the minimum level at a later stage. (programatically)

That said, the writeTo function also has an override which allows you to supply a LogEventLevel without setting up a levelswitch. 

For example:
.writeTo(seq(""), LogEventLevel.Warning)

**Comment by mjnorman** [comment]
Maybe I am missing something in my config.  When I try .writeTo(seq()) I get that seq is not a valid method.

The only way I've been able to get the code to compile is by doing the below

```
		LoggingLevelSwitch levelswitch = new LoggingLevelSwitch(LogEventLevel.Verbose);

		Log.setLogger(new LoggerConfiguration()		
			.writeTo(new SeqSink("http://xxx/", "lT2kjQ2hGqlKAEQhvXR", null, Duration.ofSeconds(2), null, levelswitch))	
					.createLogger());
		
		Log.verbose("Hello from app");
```

However the message never reaches Seq.  I'm able to use serilog in .net with no issues.

**Comment by 80dB** [comment]
If your app quits too fast (e.g. if this is your app and it exits after the verbose) then the logger doesn't have time to send it to seq. It's an issue which I don't really know how to solve in Java :)

**Comment by mjnorman** [comment]
So as far as config, the above should be working?

**Comment by 80dB** [comment]
Looking at the config it seems right.  You could add '.writeTo(rollingFile("test-{Date}.log"), LogEventLevel.Verbose)'  to see if it at least logs to a file.

**Comment by mjnorman** [comment]
Ok I managed to finally get this working.  When you create the SeqSink, and set the levelswitch to an initial value, that value does not get assigned to the minimum log level.  So since I was not setting it manually, minimum log level by default is Information, so the write was actually never going all the way through.

Might make sense to have the SeqSink initial levelSwitch be assigned to the minimum Log level upon creation?
