### ISSUE TITLE
Orphaned Timer threads on Tomcat

### ISSUE THREAD

**Issue by mjnorman** [80dB/serilogj#5]
Hello there.  I'm noticing that after utilizing serilogj in a Tomcat environment, TimerTask threads are being orphaned and left running.  Any ideas on how it could be cleaned up so as to clear these threads?

**Comment by 80dB** [comment]
The issue is probably in PeriodicBatchingSink; it's responsible for the batch processing of events to Seq. Seeing as it's the only place in the project that uses Timers.

Could you add the following line:
timer.purge();

To PeriodicBatchinkgSink.java under "task.cancel()" at line 117 and 203.

It seems that the Timer class keeps a queue of TimerTasks that have finished or are canceled. That line should clear the queue.

**Comment by mjnorman** [comment]
Apologies for the delay, for some reason I stopped watching this issue.  On latest clone, it shows me task.cancel() is line 170 in PeriodicBatchingSink.java, but will give it a try.

**Comment by 80dB** [comment]
I've added the purge on two locations just now, it should fix the issue you saw.

**Comment by mjnorman** [comment]
I also played with purge, and it didn't really have the desired effect.  Been reading up on it and it seems like the thread needs to break from the inside.  Wouldn't it need to do something like the below?

`Thread loop = new Thread(
  new Runnable() {
    @Override
    public void run() {
      while (true) {
        if (Thread.interrupted()) {
          break;
        }
        // Continue to do nothing
      }
    }
  }
);
loop.start();
loop.interrupt();`

**Comment by 80dB** [comment]
Well it should never start a new TimerTask until the old TimerTask has been fully executed. Maybe I should rewrite this into a single threaded solution instead of using TimerTask's. Using a timer works fine in C# but apparently it's a little bit of a hassle in Java.

**Comment by mjnorman** [comment]
Just wanted to post a note that I have this running in production environment and it's looking good.  No threads running for longer than a few seconds.  Thanks!

**Comment by nblumhardt** [comment]
That's great - thanks for closing the loop @mjnorman
