### ISSUE TITLE
without using UserDestructor object, UserName is not getting included in the log

### ISSUE THREAD

**Issue by ritchieroi** [80dB/serilogj#7]
1. Log.setLogger(new LoggerConfiguration()
				.setMinimumLevel(LogEventLevel.Verbose)
{Exception}"))
				.writeTo(rollingFile("test-{Date}.log"))
				.createLogger());
//I did not use UserDestructor

2.  	User user = new User();
			user.setUserName(System.getProperty("user.name"));
			Log.forContext(JavaConsole.class).warning("Hello {name} from {@user}", "World", user);
			Log.information("Hello {name} from {@user}", "World", user);
3.  Output

2017-09-02 00:24:43.170 SGT [Information] Hello "World" from User { userId: 0 }
userName is not getting included in the log eventhough it has a public accessor method.

**Comment by nblumhardt** [comment]
Just having a poke around in the code, it looks like only fields are currently accounted for:

https://github.com/80dB/serilogj/blob/master/src/serilogj/parameters/PropertyValueConverter.java#L209

It seems like it would be natural to include gettable properties by default - @80dB what do you think?

**Comment by 80dB** [comment]
Strange, I would have expected the serializer to pickup the "property" too. The boon library is nice, but the lack of documentation is a little bit disturbing. 

According to the documentation:
Gets a list of fields merges with properties if field is not found.

https://github.com/advantageous/boon/blob/master/reflekt/src/main/java/io/advantageous/boon/core/reflection/Reflection.java#L304

So it should actually work. 

Unlike C#, Java doesn't really seem to have properties, just "emulating" properties using set/get methods.  I'm a little bit surprised it's not working on userName. It seems to do the job just fine in our production environment.

**Comment by nblumhardt** [comment]
>  if field is not found

Perhaps the issue is that there _is_ a public field, so property reflection is skipped? @ritchieroi how does that theory stack up against reality? :-)

**Comment by 80dB** [comment]
@ritchieroi I think the issue is fixed now, using another reflection method it now returns both the userId and userName and no private/protected fields (tested this too), so should be exactly what we expect.

**Comment by ritchieroi** [comment]
Works great.   Thanks guys.
